apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world-10
  labels:
    123.abc.com/job-type: normal
    123.abc.com/job-area: abc
spec:
  schedule: "*/3 * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  WorkflowMetadata:
    labels:
      abc.123.com/job-type: super
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world"]
