apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world-10
  labels:
    123.abc.com/job-type: normal
    123.abc.com/job-area: abc
spec:
  schedule: "*/3 * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: runcronjob
    # serviceAccountName: argoadmin
    volumes:
      - name: workdir
        hostPath:
          path: /data
    templates:
      - name: runcronjob
        steps:
          - - name: runproductpipelinejob
              template: runproductpipelinejob
      - name: runproductpipelinejob
        container:
          image: python:3.7.6-buster
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - pip install --upgrade pip;
              pip install -r /data/product_pipeline/requirements.txt;
              python /data/product_pipeline/product_pipeline_europe.py;
          volumeMounts:
            - name: workdir
              mountPath: /data
    
