apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wonderful-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/quangqt/ago-ci-cd.git
    targetRevision: HEAD
    path: workflow
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
