apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argoadmin-pod-patcher
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argoadmin
  namespace: argo
roleRef:
  kind: Role
  name: pod-patcher
  apiGroup: rbac.authorization.k8s.io
