name: Upload File to Azure Storage Explorer

on:
  push:
    branches:
      - main
    paths:
      - data/**

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Azure CLI
        run: |
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Copy file and folder to another path
        run: |
          sh ./copy_and_create.sh
      - name: Upload file to Azure Storage Explorer
        env:
          AZURE_STORAGE_CONNECTION_STRING: test
          AZURE_STORAGE_CONTAINER_NAME: test
        run: |
            az storage file upload-batch -s file_upload -d $AZURE_STORAGE_CONTAINER_NAME --connection-string $AZURE_STORAGE_CONNECTION_STRING


