name: Copy File to Azure Storage Explorer

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Upload file to Azure Storage Explorer
        env:
          AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=f679f04b37dee493b944601;AccountKey=KjgA4UutKLPX9XfnJ8i8tDkcrUlmRGUWeyHNUcSe3m3D0jR4YyHF6lnksc9PJIS209RDrFSir4ml+ASt6AyxAQ==;FileEndpoint=https://f679f04b37dee493b944601.file.core.windows.net/;
          AZURE_STORAGE_CONTAINER_NAME: pvc-3baacfd9-ed9a-4a85-aa73-a22f6ef79aba
          AZURE_ACCOUNT_NAME: f679f04b37dee493b944601
          AZURE_ACCOUNT_KEY: KjgA4UutKLPX9XfnJ8i8tDkcrUlmRGUWeyHNUcSe3m3D0jR4YyHF6lnksc9PJIS209RDrFSir4ml+ASt6AyxAQ==
        run: |
          az storage blob download-batch --source-container $AZURE_STORAGE_CONTAINER_NAME --destination data --connection-string $AZURE_STORAGE_CONNECTION_STRING

